global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'edgeplug-marketplace'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # EdgePlug Marketplace API
  - job_name: 'edgeplug-marketplace'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['marketplace:8080']
    scrape_timeout: 5s
    honor_labels: true

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    metrics_path: '/minio/v2/metrics/cluster'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Alert rules
# groups:
#   - name: edgeplug-marketplace
#     rules:
#       - alert: HighErrorRate
#         expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
#         for: 5m
#         labels:
#           severity: warning
#         annotations:
#           summary: "High error rate detected"
#           description: "Error rate is {{ $value }} errors per second" 
