server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  max_body_size: 10485760  # 10MB

database:
  host: "localhost"
  port: 5432
  user: "edgeplug"
  password: "edgeplug_password"
  dbname: "edgeplug_marketplace"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  expiration: "24h"
  issuer: "edgeplug-marketplace"

storage:
  type: "local"  # local, s3, minio
  local_dir: "./uploads"
  s3:
    region: "us-east-1"
    bucket: "edgeplug-marketplace"
    access_key_id: ""
    secret_access_key: ""
  minio:
    endpoint: "localhost:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    use_ssl: false
    bucket: "edgeplug-marketplace"

security:
  rate_limit_requests: 100
  rate_limit_window: "1m"
  cors_origins:
    - "*"
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"

metrics:
  enabled: true
  port: "9090"
  path: "/metrics"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output_path: "" 