# Voltage Event Detection Model Specification
# EdgePlug ML Model Tool-chain Configuration

model:
  name: "voltage_event_detector"
  version: "1.0.0"
  architecture: "lightweight_cnn"
  
  # Input specifications
  input:
    window_size: 128
    sample_rate: 1000  # Hz
    channels: 2  # voltage, current
    data_type: "float32"
    
  # Output specifications  
  output:
    classes: 2  # normal, voltage_event
    activation: "softmax"
    
  # Model architecture
  layers:
    conv1:
      filters: 16
      kernel_size: [3, 3]
      activation: "relu"
      padding: "same"
    conv2:
      filters: 32
      kernel_size: [3, 3]
      activation: "relu"
      padding: "same"
    global_pool:
      type: "global_average_pooling2d"
    dense1:
      units: 64
      activation: "relu"
      dropout: 0.3
    dense2:
      units: 2
      activation: "softmax"

# Training configuration
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: "adam"
  loss: "categorical_crossentropy"
  
  # Data augmentation
  augmentation:
    noise_std: 0.01
    time_shift: 0.1
    scaling: [0.9, 1.1]
    
  # Early stopping
  early_stopping:
    patience: 10
    min_delta: 0.001
    
  # Validation
  validation_split: 0.2
  test_split: 0.1

# Quantization settings
quantization:
  method: "dynamic_range"
  target_size_kb: 16
  input_scale: "auto"
  output_scale: "auto"
  
  # Quantization-aware training
  qat:
    enabled: true
    epochs: 10
    learning_rate: 0.0001

# Performance targets
performance:
  inference_time_us: 500  # ≤500µs on M4 @80MHz
  model_size_kb: 16       # <16KB quantized
  accuracy_threshold: 0.98  # ≥98% precision
  recall_threshold: 0.95   # ≥95% recall
  
# Invariant bounds for safety
safety:
  voltage_bounds: [0.8, 1.2]  # 80% to 120% of nominal
  current_bounds: [0.5, 2.0]  # 50% to 200% of nominal
  response_time_ms: 100        # ≤100ms response time
  
# Reproducibility
reproducibility:
  seed: 42
  deterministic: true
  mixed_precision: false
  
# Export settings
export:
  format: "tflite_micro"
  target: "cmsis_nn"
  optimization: "int8"
  
  # C code generation
  c_code:
    output_dir: "artifacts/c_code"
    model_name: "voltage_event_model"
    tensor_arena_size: 2048  # 2KB for inference
    
# CI/CD integration
ci:
  nightly_retrain: true
  model_registry: "edgeplug-models"
  versioning: "semantic"
  
# Testing configuration
testing:
  adversarial:
    enabled: true
    method: "fgsm"
    epsilon: 0.01
    
  robustness:
    noise_injection: true
    data_corruption: true
    boundary_testing: true
    
# Documentation
documentation:
  model_card: true
  performance_report: true
  safety_analysis: true 